# Numpy:

## Arrays

- ##### It is a data structure ndarray and it has which makes working with it very easy and it is highy used for doing fast numerical computations.
- ##### Numpy arrays can only have one data type.

In [1]:
import numpy as np

#### General infomation about array

In [28]:
# Declaration of array can be done in many ways: it can be directly initialised as a numpy arrat or a normal list can be converted to the numpy array.
arr1=np.array([1,2,3,4,5])
print(f"- This is the numpy array:\n\t{arr1}",end="\n\n")

# We can also declare the dtype for the array created and display the different features of the array such as dimensions, shape and data type.
arr1_dec=np.array([[1,2,3],[4,5,6]], dtype=np.float32)
print(f"- The dimensions, shape and data type for the array given below are {arr1_dec.ndim}, {arr1_dec.shape} , {arr1_dec.dtype}.\n{arr1_dec}",end="\n\n")

new_arr2=np.array([[1,2,3],[4,5,6]], dtype=np.float32)

# The below are the examples of the concept called Broadcasting.
arr2 = arr1 + 2
print(f"- Adding any number directly to the array variable adds it to every element of the array.\n\t{arr2}",end="\n\n")

arr3 = arr1 * 2
print(f"- Multiplying any number directly to the array variable multiplies it to every element of the array.\n\t{arr3}",end="\n\n")

- This is the numpy array:
	[1 2 3 4 5]

- The dimensions, shape and data type for the array given below are 2, (2, 3) , float32.
[[1. 2. 3.]
 [4. 5. 6.]]

- Adding any number directly to the array variable adds it to every element of the array.
	[3 4 5 6 7]

- Multiplying any number directly to the array variable multiplies it to every element of the array.
	[ 2  4  6  8 10]



A similar function to the ones function above is the zeroes function which returns an ndarray containing zeroes.

In [6]:
arr3=np.arange(1559,1563)
print(arr3)

[1559 1560 1561 1562]


np.arrange creates an one-dimensional array b\w the given numbers.

In [14]:
new=np.array([[1.2,2.2,3.2],[4.2,5.2,6.2],[7.2,8.2,9.2]], dtype=np.float32)
print(new)
print(new.astype(np.uint16))

[[1.2 2.2 3.2]
 [4.2 5.2 6.2]
 [7.2 8.2 9.2]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
a=np.ones((2,2,3))
b=np.zeros_like(a)
print(b)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [26]:
arr90=np.random.random((4,4))
arr90*=100
print(arr90)

[[85.92986301 16.61643431  4.19352348 29.10275078]
 [93.60219756 69.96160099 75.10390112 62.90139152]
 [23.51649442 42.99395027 42.46942849 29.2471812 ]
 [76.91292278 59.27135069 26.08847885 92.0627941 ]]


In [27]:
temp2=np.ones([7,8])
print(type(temp2))
print(temp2)

<class 'numpy.ndarray'>
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [28]:
arr45=np.array([1,2,3])
arr46=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr47=arr45+arr46
print(arr47)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


SHAPING:


In [31]:
arr48=np.array([1,2,3,5,4,6])
arr48=arr48.reshape(3,2)
print(arr48)
arr48=arr48.reshape(2,-1)
print(arr48)
arr48=arr48.ravel()
print(arr48)

[[1 2]
 [3 5]
 [4 6]]
[[1 2 3]
 [5 4 6]]
[1 2 3 5 4 6]


Total number of elements cannot change.
Use -1 to infer axis shape.
Row-major by default. Here note the difference that MATLAB is column-major.


In [36]:
test=[1,2,3]
x=np.array(test)
print(x)
y=np.array([[1,2,3],[4,5,6]])
z=x*y
print(z)
z=x/y
print(z)

[1 2 3]
[[ 1  4  9]
 [ 4 10 18]]
[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]


Transposition is a function through which we perform the operation of 

In [39]:
we=[1,4,9,16,25,36,49,64,81,100]
new90=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
new90=np.sqrt(new90)
print(new90)

[[[1.         1.41421356]
  [1.73205081 2.        ]]

 [[2.23606798 2.44948974]
  [2.64575131 2.82842712]]]


Slicing can be done similar to the list slicing.

### Elements can be added in the dataframe by using the `insert` method
```python
np.insert( x_train, obj=0, values=1, axis=1 )  # obj: column before which value array is to be inserted; values: values whose column is to be added
```

## __np.linalg class__

`np.linalg.inv`: It finds out the inverse of the matrix